# https://github.com/jdx/mise#configuration
[tools]
poetry = {version='2.0.0'}
python = {version='3.13.1'}
node = {version='22'}

[settings]
experimental = true

[env]
TERRAGRUNT_TFPATH = "tofu"
_.python.venv = { path = ".venv", create = true, python = "3.13.1" }
