# https://github.com/jdx/mise#configuration
[env]
TERRAGRUNT_TFPATH = "tofu"

[tools]
poetry = {version='1.8.5'}
python = {version='3.13.1', virtualenv='.venv'}
node = {version='22'}

[settings]
experimental = true
python_venv_auto_create = true
