name: "Run install"

runs:
  using: "composite"
  steps:
    - name: install
      run: ./install.sh
      shell: bash
      working-directory: ${{ github.workspace }} # explicitly set working directory

    - name: chezmoi data
      run: '"$HOME/.local/bin/chezmoi" data'
      shell: bash
