name: check

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  run-install-test:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ["ubuntu", "debian"]
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:${{ matrix.distro }}
      env:
        CODESPACES: true
        REMOTE_CONTAINERS: true
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      # install for lint and test
      - uses: ./.github/actions/run-install
      - run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: setup
        run: |
          make setup
        shell: bash -leo pipefail {0}
      - name: mise env
        uses: ./.github/actions/mise-hook-env
      - name: lint
        run: |
          make lint
        shell: bash -leo pipefail {0}
      - name: test
        run: |
          make test
        shell: bash -leo pipefail {0}

  run-install-vm:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: ./.github/actions/run-install

  super-linter:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          # for super-linter
          fetch-depth: 0
      - name: load env
        run: |
          grep -v '#' .superlinterenv >> "$GITHUB_ENV"
      - uses: super-linter/super-linter/slim@5b638caee6ba65e25e07143887b669a1233847a0 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
