name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-install-test:
    strategy:
      matrix:
        distro: ["ubuntu", "debian"]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:${{ matrix.distro }}
      env:
        CODESPACES: true
        REMOTE_CONTAINERS: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-install
      - run: |
          echo "AQUA_GLOBAL_CONFIG=$HOME/.config/aquaproj-aqua/aqua.yaml" >> $GITHUB_ENV
      - name: test
        shell: bash --login -eo pipefail {0}
        run: |
          aqua i -a
          make test

