name: check

on:
  push:

jobs:
  run-install:
    strategy:
      matrix:
        distro: ["ubuntu", "debian"]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:${{ matrix.distro }}
      env:
        CODESPACES: true
        REMOTE_CONTAINERS: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-install
