name: "Pull Request Labeler"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # use GitHub Apps token to run other actions.
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ steps.gh-app-token.outputs.token }}
