name: "Rebase PRs auto merge enabled"

on:
  pull_request:
    types:
      - closed

permissions: {}

jobs:
  rebase-auto-merge-enabled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
      - name: rebase
        uses: air-hand/common-actions/update-prs-auto-merge-enabled@c30d729c959d4b09660395a7cc8fd43af05911fb # v1.0.0
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          base_branch: main
